### ISSUE TITLE
Getting error of Missing required parameters: siteHandle

### ISSUE THREAD

**Issue by developer-murtazavhora** [OliveStudio/olivemenus#41]

**Comment by gbaumbach** [comment]
I am receiving the same error

**Comment by niektenhoopen** [comment]
@developer-murtazavhora @gbaumbach There are more issues since the multi-site option was added. Migrations are not run, links / routing does not work and then I am probably not even done yet. I will create separate issues for those.

The work-around would be to add ?siteHandle=[your-site-handle] to the URL but you run into the problem that migrations are probably not run yet #42 

After the migrations are run, the current menus still need the site ID... etc.

I am not sure if I am able to create a pull request for all these issues because I honestly don't know what all needs to be fixed.

You are probably better off by requiring version 1.1.16 in your composer.json. (Which is basically a downgrade but should be possible because the database migrations are probably not migrated anyway)

**Comment by alinistrate** [comment]
@niektenhoopen please open issues for each item. 
We will look into it

Thank you,
Alin
